### ISSUE TITLE
Navigation arrows in scroll/horizontal orientation

### ISSUE THREAD

**Issue by siennamw** [ahwitz/Vida6#10]
When I switch from vertical to horizontal orientation, whichever arrow was active remains visible but does nothing when I click it.  I'm guessing that you intended for both arrows to be deactivated for the horizontal orientation, and I think that would be the best/quickest solution here.

**Comment by ahwitz** [comment]
Should be fixed. Let me know if that's good.

**Comment by siennamw** [comment]
All better.  Thanks!
