### ISSUE TITLE
Can't scroll vertically when in horizontal orientation

### ISSUE THREAD

**Issue by siennamw** [ahwitz/Vida6#11]
In horizontal orientation, when there are more than a few parts or when I'm zoomed in, I can't see all the staves in the viewport.  When I try to scroll down to see the off-screen staves, nothing happens.  I can scroll horizontally (and vertical scroll works in vertical orientation), but the only way to see the other staves in horizontal orientation is to zoom out.

**Comment by ahwitz** [comment]
Should be fixed. Let me know if that's good.

**Comment by siennamw** [comment]
Yup, it's fixed.  Thanks!
